### ISSUE TITLE
📚 Recomendação do livro • Engenharia de Software Uma Abordagem Profissional - Autor Roger S. Pressman

### ISSUE THREAD

**Issue by michelereginabora** [KAYOKG/BibliotecaDev#16]
### O que esse livro tem a agregar?

É uma obra abrangente sobre os fundamentos e práticas da engenharia de software. Ele cobre o ciclo de vida completo do desenvolvimento de software, incluindo análise de requisitos, design, codificação, testes e manutenção, enfatizando métodos modernos e boas práticas profissionais.

**Comment by ummm288** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
