### ISSUE TITLE
📚 Recomendação do livro • Mergulho nos
PADRÕES de PROJETO - Autor Refactoring Guru

### ISSUE THREAD

**Issue by NatanB4** [KAYOKG/BibliotecaDev#5]
### O que esse livro tem a agregar?

Ótimo livro em geral que explica com imagens e um breve resumo claro como utilizar e os prós e contras de cada patern. (Inclusive tenho caso queira.)

**Comment by KAYOKG** [comment]
Realmente, possui muito a agregar, @jpsoarxs contribuiu com um Pull Request ao projeto, agradeço aos 2.
